  services:  
    prometheus:
      image: my-prometheus 
      container_name: monitoring_prometheus
      restart: unless-stopped
      volumes:
        - ./data/prometheus/config:/etc/prometheus/
        - ./data/prometheus/data:/prometheus
      ports:
        - 9090:9090
    grafana:
      image: grafana/grafana
      container_name: grafana
      restart: unless-stopped
      volumes:
        - ./data/grafana:/var/lib/grafana
      ports:
        - 3000:3000
      
